export const events = [
  {
    id: 1,
    title: "Vacation",
    allDay: true,
    start: new Date(2021, 10, 21),
    end: new Date(2021, 10, 23),
    eventDetail: "Going to Disneyland!!!!!!!",
    eventType: "vacation",
    color: "#30b4d1",
  },
  {
    id: 2,
    title: "Meeting with Jeff",
    allDay: false,
    start: new Date(2021, 10, 18, 9, 30),
    end: new Date(2021, 10, 18, 10, 0),
    eventDetail: "Talk to Jeff about the project",
    eventType: "important",
    color: "#d60404",
  },
  {
    id: 3,
    title: "Last day of school",
    allDay: true,
    start: new Date(2021, 11, 14),
    end: new Date(2021, 11, 14),
    eventDetail: "Last day of school!!!!!!!!!!",
    eventType: "personal",
    color: "#02970f",
  },
  {
    id: 4,
    title: "Bake Sale",
    allDay: true,
    start: new Date(2021, 10, 24),
    end: new Date(2021, 10, 24),
    eventDetail: "Make Cookies",
    eventType: "personal",
    color: "#02970f",
  },
  {
    id: 5,
    title: "Doctor Appointment",
    allDay: false,
    start: new Date(2021, 10, 26, 9, 0),
    end: new Date(2021, 10, 26, 11, 0),
    eventDetail: "Bring your insurance card",
    eventType: "personal",
    color: "#02970f",
  },
];
